# -*- coding: utf-8 -*-
"""visuals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BWo_soj0rLq5GgtoU-2tnANmujD5sicl

# Importing Libraries
"""

import pandas as pd 
import numpy as np
import seaborn as sns
import streamlit as st
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import matplotlib.pyplot as plt

"""# Reading csv dataset on the BBI Knowledge"""

df1=pd.read_csv('streaBBI_Knowledge.csv')
df1

"""# Visualization."""

# data1=df1['knowledge']
# y=df1['respondents']
# fig = plt.figure(figsize =(8, 6))
# colors = sns.color_palette('pastel')[0:4]
# plt.pie(y, labels=data1, colors= colors,autopct='%1.2f')
# plt.legend()
# plt.title('Full knowledge on BBI')
# plt.show()
figa = px.pie(df1, values=df1['respondents'], names=df1['knowledge'], title='Full knowledge on BBI')
st.plotly_chart(figa)
#bar chart
fig_1 = px.bar(df1, x=df1['knowledge'], y=df1['respondents'],title="Full knowledge on BBI", barmode='group',
hover_data=['respondents', 'knowledge'], color='respondents', height=500)
# st.dataframe(df) # if need to display dataframe
st.plotly_chart(fig_1)

"""# Reading csv dataset on What BBI wants to change"""

changes=pd.read_csv('BBI_changes.csv')
changes

"""# Visualizing it."""

# data2=changes['knowledge']
# y=changes['number_of_respondents']
# fig = plt.figure(figsize =(8, 6))
# colors = sns.color_palette('pastel')[0:4]
# plt.pie(y, labels=data2, colors= colors,autopct='%1.2f')
# plt.legend()
# plt.title('What BBI wants to change')
# plt.show()
figb= px.pie(changes, values=changes['number_of_respondents'][:3], names=changes['knowledge'][:3], title='What BBI wants to change')
st.plotly_chart(figb)

"""# Reading csv dataset on where respondents get news from """

dfNews=pd.read_csv('newsSource.csv')
dfNews

"""# Visualizing it."""

# news=dfNews['sources_of _news']
# respondents=dfNews['number_of_respondents']
# fig = plt.figure(figsize =(10, 8))
# sns.set_palette("gist_rainbow_r")
# sns.barplot(x=news, y=respondents).set_title("Where do you get your news from?")
# plt.xlabel('Source of news')
# plt.ylabel('Number of respondents')
# plt.show()
figc = px.pie(dfNews, values=dfNews['number_of_respondents'], names=dfNews['sources_of _news'], title='Where do you get your news from?')
st.plotly_chart(figc)

fig_4 = px.bar(dfNews, x=dfNews['sources_of _news'], y=dfNews['number_of_respondents'],title="Where do you get your news from?", 
barmode='group',hover_data=['number_of_respondents', 'sources_of _news'], color='number_of_respondents', height=500)
# st.dataframe(df) # if need to display dataframe
st.plotly_chart(fig_4)

"""# Reading csv dataset on BBI regional support.

"""

regional_support=pd.read_csv('regional_support.csv')
regional_support

"""# Visualizing."""

# regions =regional_support['County']
# yes_val=regional_support['yes']
# no_val=regional_support['no']
# thinking_about_it=regional_support['thinking_about_it']
# don_t_care=regional_support['don_t_care']
# #ploting bar graph 
# fig = plt.figure(figsize =(15, 10))
# sns.set_palette("gist_rainbow_r")
# bar_plot1 = sns.barplot(y=regions, x=yes_val, label="yes", color="red")
# bar_plot2 = sns.barplot(y=regions, x=no_val, label="no", color="blue")
# bar_plot3 = sns.barplot(y=regions, x=thinking_about_it, label="thinking about", color="purple")
# bar_plot4 = sns.barplot(y=regions, x=don_t_care, label="dont care", color="orange")

# #plt.legend(ncol=4, frameon=True)
# plt.title("Support per Region")
# plt.legend(bbox_to_anchor= (1.2,1))
# plt.show()
fig5= px.bar(regional_support, y=regional_support['County'], x=[regional_support['yes'], regional_support['no'], regional_support['thinking_about_it'],regional_support['don_t_care']], title="Support per Region", height=600)
st.plotly_chart(fig5)